### ISSUE TITLE
Playing an Internet stream

### ISSUE THREAD

**Issue by ArtSpaziano** [txoof/querylms#3]
I didn't see a method that could be used for playing an Internet stream (ex: http://opml.radiotime.com/Tune.ashx?id=s24062&formats=aac,ogg,mp3&partnerId=16&serial=b1fc80c602f6c15efa6820d7fe81bfee )

This would be pretty handy for sending sound notifications as well as streaming Internet radio stations on the players.

If it is possible using one of the existing methods, please let me know what I missed.

**Comment by txoof** [comment]
I borrowed a good chunk of this code from [LMSQuery](https://github.com/roberteinhaus/lmsquery); there were some methods that weren't entirely documented in LMSQuery that I ported over without ever completely figuring out what they did.

You could try [`play_radio(self, radio)`](https://github.com/txoof/querylms/blob/2ff1703b35eb92295a7a1bb9306884dbf837894b/QueryLMS/QueryLMS.py#L503-L506). 

If that doesn't do it, if you can find an API reference that documents what you want, we can add it in.

**Comment by ArtSpaziano** [comment]
Thanks. I did try play_radio but it didn't work. I didn't check the LMS log to see if there were any clues but I will look into that and any API references.    
I'm currently doing this with cVLC for sending pre-recorded messages to remote speakers in the house which already have squeezebox clients. If I can get this working through the LMS API, I can remove xVLC on the speakers.

**Comment by ArtSpaziano** [comment]
Ok, Aaron, I believe I have it sorted.
The play_radio function only takes the "Favorite" ID # from your list of favorites ("0" is the first favorite).
It does not accept a URL. When I tried, it somehow parsed an integer from the string and interpreted as the URI of the corresponding favorite.

Watching the LMS log, I see that this line is passed when starting an internet stream on a player UI:
 Slim::Plugin::CLI::Plugin::client_socket_write (463) 192.168.1.106:49848 - Sending response [b8%3A27%3Aeb%3Aa8%3Af2%3A29 playlist play https%3A%2F%2Fnebcoradio.com%3A8443%2FWXRV
I believe the URL encoding part is done by the CLI.

A added the following to QueryLMS.py  just below the play_radio function:
    def play_stream(self, url):
        '''play stream url on associated player'''
        return self.query(self.player_id, "playlist", "play", str(url))

Now, when I run the following program, it actually plays an Internet stream!

>>> from QueryLMS import QueryLMS
>>> office_player = QueryLMS(host="192.168.1.104", port=9000, player_name="Office")
>>> office_player.play_stream("https://nebcoradio.com:8443/WXRV")

Also works with HTTP hosted sound effects files:

>>> office_player.play_stream("https://www.pacdv.com/sounds/domestic_sound_effects/phone_1.wav")

It would be great if you could incorporate this new function into the code so others can benefit.

**Comment by txoof** [comment]
@ArtSpaziano 

I'd be happy to add that function in. PRs are welcome! Would you be able to submit one? If you're unfamiliar with the workflow, let me know and I can walk you through it. As you've already made the changes in your local copy of QueryLMS, it's pretty simple.

Also, some documentation about what you discovered regarding the `play_radio` function would be helpful.

to be clear is this roughly the method you are proposing to add?

```python
def play_stream(self, url):
   '''play stream url on associated player'''
   return self.query(self.player_id, "playlist", "play", str(url))
```

**Comment by ArtSpaziano** [comment]
Yes, that's the method I added.
I have not submitted pull requests before but have worked with code management systems in the past (I'm a 70 year old retired software development managed!).
I'll be away for most of the day today but I'll check out some documentation on the the process and see if I can submit the change.

**Comment by txoof** [comment]
@ArtSpaziano Fantastic!

If it turns into too much of a project, let me know and I'll add it when I have some time. I'm hip-deep in sorting out another issue.

**Comment by ArtSpaziano** [comment]
I just made the pull request after forking and making my changes.
'still not sure I got it right so check things on your end when you get the chance.

**Comment by ArtSpaziano** [comment]
Closing this issue. play_stream is now part of the distrubution

**Comment by txoof** [comment]
Thanks for the PR! 

I still need to publish this to PyPi - that will take a bit because I still need to configure the new trusted publisher settings.

**Comment by txoof** [comment]
@ArtSpaziano 

You learned how to submit a PR, and I learned how to publish a package to PyPi with the new Trusted Projects feature. Banner day!

Thanks again for the PR! Future PRs are definitely welcome.

**Comment by ArtSpaziano** [comment]
A day that passes without learning something is a day lost, in my estimation.
In any case, you are welcome. As I try to transition away from cvlc dependency, I may find more functionality to add but this gets me started.

**Comment by txoof** [comment]
Indeed. Learning is amazing, but sometimes learning is **hard**.  At least I now have a fairly comprehensive [gist](https://gist.github.com/txoof/41fee9b199e9bc2114bcce1fc8315579) that covers how to publish to PyPi. And two hours ago, I thought this was going to be a 10 minute job.

what is cvlc dependency?

**Comment by ArtSpaziano** [comment]
Ha! I learned that 10 minute jobs are equivalent to the mythical unicorn around 50 years ago. It applies to car repair, home maintenance and software development. 'not sure what it is but I still believe and they still [mostly] elude me.

cvlc is the command line version of the media player VLC ( https://www.videolan.org/ ).
It has the option of enabling an embedded server in each player instance. You can send it a HTTP post with a URL and it will play the stream. 
I've been using it to send various smart home (via Hubitat) messages for certain events to Raspberry Pi based smart speakers around the house. Examples: Front door planter needs watering, someone is at the front door, Unread email waiting for (family member name) .....

I also have a LMS client installed on those speakers which works for TTS messages from Hubitat but not for custom, Python programs I created outside of Hubitat.  I was forced to go the VLC route.... until this weekend, thanks to your code and a small modification.

**Comment by txoof** [comment]
glad I could help and glad you found a solution.

If you've got some pis running around the house, check out this project: https://github.com/txoof/PaperPi

I adopted QueryLMS to make it easy to display "now playing" information on epaper screens. PaperPi has a plugin that lets you see what's currently playing on an LMS host or raSpotify instance.

It's only currently working with Bullseye32, but I'm working on getting it ready for Bookworm32.
